### ISSUE TITLE
After updating to 0.2.5, explicit newlines in strings are no longer accepted as valid

### ISSUE THREAD

**Issue by xxx** [AzureMarker/intellij-lalrpop#47]
Hi,

I just updated my plugin, and am now seeing an error for the following construct:

```rust
unreachable!("This only way for this to be reached is if a new op was added in the parent `match`, \
              without updating the TryFrom implementation, which shouldn't compile.")
```

with an (escaped) embedded newline. This is valid, and the grammar works fine - it's just the plugin now marks everything around and below it as an error.

If I remove the embedded newline and put the message onto a single line, the syntax is seen as valid.

**Comment by AzureMarker** [comment]
I fixed the issue and submitted v0.2.6 to the plugin marketplace. Thanks for opening the issue!
