### ISSUE TITLE
Running unit tests through intelliJ does not recompile or detect changes in Lalrpop grammar

### ISSUE THREAD

**Issue by evbo** [AzureMarker/intellij-lalrpop#53]
Not sure if its this plugin, but if I use IntelliJ's built-in run commands it executes without recompiling lalrpop grammar first so changes are not picked up. I don't remember this being an issue a few months ago.

As a work around, I then have to go into my Tauri app's target directory and manually delete app folders so that it recompiles:
`project/src-tauri/target/debug/build/app-b0b65191693b0be0`

Is this in your wheel well or should I report this issue somewhere else?

**Comment by AzureMarker** [comment]
That's most likely not related to this plugin, since it just parses the grammar file to make editing it in your IDE easier. The actual building is all through normal Cargo mechanisms. Do you have the source publicly available, or is your build.rs more complicated than just `lalrpop::process_root().unwrap();`? (from [the book](http://lalrpop.github.io/lalrpop/quick_start_guide.html))

**Comment by evbo** [comment]
Thanks I can close if not related to this repo but FWIW this is all I'm doing in build.rs:

```rust
extern crate lalrpop;

fn main() {
  lalrpop::process_root().unwrap();
  tauri_build::build()
}
```

And yes, following the book

**Comment by AzureMarker** [comment]
You could use this to ensure the build script gets rerun on changes to the grammar file, though I expect LALRPOP should be doing this already (haven't checked):
https://doc.rust-lang.org/cargo/reference/build-scripts.html#rerun-if-changed

**Comment by AzureMarker** [comment]
@evbo I think your other `tauri_build` command may be outputting rerun directives, in which case the build script isn't re-executed when the lalrpop file changes. By default lalrpop doesn't emit rerun directives:
https://github.com/lalrpop/lalrpop/blob/d45124db36919e8a70a04581745b156fdeafbe92/lalrpop/src/api/mod.rs#L105-L109

But it looks like you can configure it to do so.
