### ISSUE TITLE
dependency error in RustRover

### ISSUE THREAD

**Issue by Efilex** [AzureMarker/intellij-lalrpop#56]
Hello,

I tried installing the lalrpop plugin via RustRovers plugin manager, but there seems to be a problem with the dependecies.
'[org.rust.lang](https://plugins.jetbrains.com/plugin/8182--deprecated-rust)' is marked as required, although that plugin seems to be deprecated?

**Comment by Efilex** [comment]
probably need to switch out the dependency with the [updated plugin](https://plugins.jetbrains.com/plugin/22407-rust)

**Comment by AzureMarker** [comment]
Just released 0.2.14 which switches to use the new Jetbrains Rust plugin. That should fix this issues.
